apiVersion: v2
appVersion: auto
dependencies:
- name: common
  repository: https://truecharts.org/
  version: 6.5.0
deprecated: false
description: Plex Media Server
home: https://github.com/TheGrimmChester/apps/tree/master/charts/stable/plex
icon: https://www.plex.tv/wp-content/uploads/2018/01/pmp-icon-1.png
keywords:
- plex
- plex-media-server
kubeVersion: '>=1.16.0-0'
maintainers:
- email: info@truecharts.org
  name: TrueCharts
  url: truecharts.org
- email: kjeld@schouten-lebbing.nl
  name: Ornias1993
  url: truecharts.org
name: plex
sources: null
type: application
version: 5.3.0
