# Default values for Plex.

image:
  repository: ghcr.io/k8s-at-home/plex
  pullPolicy: IfNotPresent
  tag: v1.22.3.4523-d0ce30438

strategy:
  type: Recreate

# 44=video 107=render
podSecurityContext:
  runAsNonRoot: true
  runAsUser: 568
  runAsGroup: 568
  fsGroup: 568
  supplementalGroups: [44, 107]

service:
  main:
    ports:
      main:
        port: 32400

persistence:
  config:
    enabled: true
    mountPath: "/config"
    type: emptyDir

env:
  ALLOWED_NETWORKS: "172.16.0.0/16"
